- siteManagerDashboard/assets/css/dashboard.css
- siteManagerDashboard/commons.js
- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantLookup.js
moving shared methods from index.js to commons.js as well as adding separate js files for navigationBar and each of the tabs on the bar
> Site manager hui

- siteManagerDashboard/assets/css/dashboard.css
- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
- siteManagerDashboard/utils.js
This PR addresses the following features & fixes:
-> Updated concept ID mapping for Participants Summary and updated metrics mapping
Related PRs #10 #9 
Checklist:
Notes: 
Site dropdown selection (in progress) is disabled temporarily. New current changes are breaking the site selection.
> Site Manager Dashboard : Update Participants concept ID & Metrics mapping

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantLookup.js
- siteManagerDashboard/siteKeysToName.js
- siteManagerDashboard/utils.js
This PR addresses the following features & fixes:
-> Participant dashboard site dropdown, lets the user view other sites dashboard. Dropdown is only available for Parent Sites
-> Mapped Site code to Site Name on Participant Commons & Participant Headers
Checklist:
- 
Notes: 
Created a new file called SiteKeysToName.js, contains site ids and ids can be updated as we move to higher environments 
Test case 1:
Check the UI dashboard for different Health Partner Sites using the Site Dropdown
Parent Dashboard:
Other site dashboard upon selecting site preference from dropdown:
> Site Manager Dashboard : Participants Site dropdown to view other sites dashboards

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
Fixed navigation error on Participant Summary. User can go backwards to Participant Details & Participant Lookup from Participant Summary & Participant Details.
#38
> Site Manager dashboard: Defect = Fixed navigation error on Participant Summary

- siteManagerDashboard/index.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantDetails.js
User can edit fields on participant details after navigating back from participant summary.
Navigate from participant details to participant lookup.
#38
> HOTFIX: Site Manager dashboard: Fixed navigation error on Participant Details

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
> Site Manager dashboard: Filter default columns in table from column buttons

- siteManagerDashboard/participantHeader.js
Date fix added to Participant Header for Verification Status
#34
> HOTFIX: Site Manager dashboard: Fix Label for Verified

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
- siteManagerDashboard/participantWithdrawalForm.js
PR address following issues raised: #58 #32 #33 #15
-> Updated variables on Participant Summary
-> Workflow metrics is now cumulatively calculated for each category
-> Hover information changed on pie charts
> Site Manager Dashboard: Defect fixes

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummaryRow.js
PR address following issues raised: #58
-> Related PRs: #61 #67
> pointing payment to issued instead of eligible

- siteManagerDashboard/navigationBar.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantWithdrawal.js
- siteManagerDashboard/participantWithdrawalForm.js
- siteManagerDashboard/participantWithdrawalRender.js
This PR address following issues: #69 
-> Added suspended date variable, variable appears only when suspended date is set
Checklist:
Test case 1:
Check for suspended date for an user:
> SiteManger Dashboard: Participant Header added suspended date

- siteManagerDashboard/participantHeader.js
This PR addresses following PR #69:
-> Added additional condition for suspended contact date to appear only for participants
with suspended date
> [HotFix] Added additional condition for suspended contact date to appear only for participants

- siteManagerDashboard/participantSummaryRow.js
> [HotFix] Added shorthand evaluation for participant refusal options

- siteManagerDashboard/index.js
This PR addresses following issue: 
#33
> [HotFix] Workflow verification count

- siteManagerDashboard/index.js
This PR ensures the recruits count for parent sites is tallied.
> [HotFix] Fix Parent Sites Recruits counter

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantLookup.js
>  [Defect] Fixed data discrepancies

- siteManagerDashboard/index.js
Removes direct commit to Master branch
> FIX MASTER BRANCH

- siteManagerDashboard/index.js
> [HotFix] Updated Total Funnel Equation

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
Filtered out inactive participants from total recruits funnel
> [HotFix] Removed console log & added a condition for total funnel

- siteManagerDashboard/participantMessages.js
This PR address following issues:
#98
> [HotFix] Participant Messages

- siteManagerDashboard/participantLookup.js
- siteManagerDashboard/participantMessages.js
> SiteManager Dashboard: Removed hardcoded & console.logs

- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantLookup.js
- siteManagerDashboard/participantMessages.js
- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard Addressed Issues

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantSummary.js
> [HotFix] Fixed Filter By Site & Other major fixes

- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
- siteManagerDashboard/participantCommons.js
#101 
And other minor changes as well
> SiteManager Dashboard : Add Site filter dropdown

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantLookup.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
> [Site Manager Dashboard] Site filter all participants

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
This PR addresses the following features:
-> Added SSN, Modules & Opt Outs Metrics Charts
Checklist:
Test Cases:
-> Test Case 1: Check metrics charts for **All** & **different sites**
PoC: 
Test case 1:
Site Selection: **All**
Test case 2:
Site Selection: **Sanford Health**
> Site Manager Dashboard: Added SSN, Modules & OptOuts Metrics Charts

- siteManagerDashboard/index.js
> [Branch Fix] Revert branch to original state

- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
Updated jQuery to version 3.6.0 from 3.40. To prevent security threats & vulnerability.
> Site Manager Dashboard: jQuery verison update

- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
>  Site Manager Dashboard: Merge DEV to Master

- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
update jQUERY version (#143) (#144)
>  Site Manager Dashboard: Merge STAGE to Master

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantSummaryRow.js
> [Site Manager Dashboard] Harmonized Metrics Data

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantSummaryRow.js
> [Site Manager Dashboard]: Fix branch

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantSummaryRow.js
> [Site Manager Dashboard] Merge DEV to STAGE

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantSummaryRow.js
> [Site Manager Dashboard]: Merge Stage to Master

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
> [HotFix]: Added missing races in Demographics Metrics

- siteManagerDashboard/utils.js
This PR addresses following fixes:
-> To maintain consistency across the application. Date/Time functions are updated & optimized to ISO format Date/Time.
-> Utilizes in built ISO functions to get timestamps
Test cases:
Following functions are updated to ISO format and changes were verified:
-> getCurrentTimeStamp()
-> humanReadableFromISO()
-> humanReadableMDY()
> [HotFix] Updated Date/Time functions to ISO format Date/Time

- siteManagerDashboard/participantSummary.js
-> Updated name & signature coordinates on consent & hipaa forms
Consent Form:
HIPAA Form:
> [HotFix] Updated name & signature coordinates on consent & hipaa forms

- siteManagerDashboard/index.js
- siteManagerDashboard/participantMessages.js
-> Participant message wasn't accessible when logged in SSO. 
This pr takes care of the issue, by using sso id token.
> [HotFix]: Participant messages edge case

- siteManagerDashboard/participantMessages.js
-> Added import statement for getIdToken in Participant Messages
Related PRs:
#160
> [HotFix] Added import statment for Participant Message

- siteManagerDashboard/participantWithdrawalForm.js
-> Participant withdrawal wasn't accessible when logged in SSO.
This pr takes care of the issue, by using sso id token.
> [HotFix]: Participant Withdrawal edge case

- siteManagerDashboard/participantDetails.js
This PR addresses following fix:
-> Captures string/character after space and doesn't discard them
> [HotFix]: Participant Details edge case 

- siteManagerDashboard/index.html
- siteManagerDashboard/participantWithdrawalForm.js
> [HotFix] Addressed Participant WIthdrawal Issue

- siteManagerDashboard/participantSummary.js
> [HotFix] Updated revocation indicator sign to cross mark for revocation rows

- siteManagerDashboard/participantWithdrawalForm.js
Title ^^
Related PR: #180 
**Data Destroy**
**Withdrew Consent**
**HIPAA Revoc**
> [Site Manager Dashboard] Added dates to destory data & withdrew consent

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantSummary.js
This PR addresses following issues raised:
#182 #183
> [SiteManager Dashboard] Addressed issues raised

- siteManagerDashboard/participantSummary.js
> [HotFix]: Fixed Revocation Download issue

- siteManagerDashboard/participantWithdrawalForm.js
This PR address following fix:
-> removed commented code
> [SiteManager Dashboard] Remove Comments

- siteManagerDashboard/participantDetails.js
> SiteManager Dashboard: Removed console.logs

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantWithdrawalRender.js
> SiteManager Dashboard: Addressed Issues

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Addressed comments #203

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantWithdrawalForm.js
-> Removed time stamps form refusal options nest
> SiteManager Dashboard: Added Refusal/Withdrawal Fix

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Added suspended until concept date to Refusal/Withdrawal

- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantHeader.js
> SiteManager Dashboard: Temporarliy disabled enrollment status

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Quick fix to Campaign Type & Duplicate Type

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
This PR addresses the following issue:
#212 #219
> SiteManager Dashboard: Added notification schema bug fixes & view feature on the retrieve

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
> SiteManager Dashboard: Notification schema View Schemap Update

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantWithdrawal.js
- siteManagerDashboard/participantWithdrawalForm.js
- siteManagerDashboard/siteMessages.js
This PR addressed following issues:
#202 #222 #238 #239 #240 #242
> Site Manager Dashboard: Addressed issues raised on refusals/withdrawals

- siteManagerDashboard/participantCommons.js
This PR addresses the following features & fixes:
-> Changed api calls to grab site specific participants
Checklist:
Test Cases:
-> Test Case 1: 
Check the Filter by Site for different Sites
PoC: 
Test case 1:
For Health Partner:
For KP NW:
For All:
> [HotFix]: Changed api calls to grab site specific participants

- siteManagerDashboard/index.js
- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: SSN& HalfSSN on metrics

- siteManagerDashboard/index.js
> SiteManager Dashboard: Removed console logs

- siteManagerDashboard/index.js
> SiteManager Dashboard: Corrected Half & Full SSN Counters

- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantWithdrawal.js
- siteManagerDashboard/participantWithdrawalForm.js
This PR addresses following feature:
-> Added Pagination & Limit filter on Dashboard
Checklist:
Test Cases:
-> Use Next button to get a next list of participants
-> Use Previous button to get a previous list of participants
-> Set limit to 20 to get 20 overall participants  
PoC:
Original List:
Next List:
Previous List:
Limit set to 20:
> SiteManager Dashboard: Pagination & Limit on Dashboard

- siteManagerDashboard/participantCommons.js
-> Added limit 10 as a default
> SiteManage Dashboard: Added limit-10 as default

- siteManagerDashboard/index.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantLookup.js
> NCI is only available for dev

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashbaord: Refusal withdrawal fixes 1/27/22

- siteManagerDashboard/participantSummary.js
> SiteManager Dashboard: Added correct ucm coordinates on forms

- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantLookup.js
> SiteManager Dashboard: Participant Page Filtering

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
> SiteManager Dashboard: Biospec survey/sample

- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Returns only site specific active/passive pts

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
> SiteManager Dashboard: Added Biospecimen metrics chart

- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantWithdrawalForm.js
Revert participant suspended date to MM/DD/YYYY format
> SiteManager Dashboard: Refusal/Withdrawal - Participant Suspeneded date

- siteManagerDashboard/fieldToConceptIdMapping.js
Corrected refusal urine survey concept id [**only on DEV**]
> SiteManager Dashboard: Update Concept ID

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantSummaryRow.js
-> Updated Verified Participants on Biospecimen metrics page #300 
-> Added N/A as default for Biospecimen Collection Setting #296
> SiteManager Dashboard: Added biospec Metrics changes

- siteManagerDashboard/participantWithdrawalForm.js
Added Who Requested All Future Activities Other.
> [Hotfix] SiteManager Dashboard quick refusal withdrawal

- siteManagerDashboard/participantSummaryRow.js
> HotFix: [SiteManager Dashboard] Replaced Particpant Module with Participant in Baseline Biospec Survey

- siteManagerDashboard/utils.js
* created function to check if participant is eligible for baseline payment round
> added logic for function

- siteManagerDashboard/utils.js
* fixed reference link to JS file
> fixed external reference link

- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Temproraliy disabled Who Requested? on Stage & Prod

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
> SiteManager Dashboard: Incentive Eligibilty row added in Participant Summary

- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Updated refusal/withdrawal data structure

- siteManagerDashboard/participantWithdrawalForm.js
Title^^
Related PR: #325
Rollback: Temporarily disabled Who Requested? on Stage
> SiteManager Dashboard: Rolled back who requested by

- siteManagerDashboard/participantCommons.js
> [Hotfix] SiteManager Dashboard: Added allBaselineSurveysCompleted field to All Participants

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantWithdrawal.js
- siteManagerDashboard/participantWithdrawalForm.js
Note: Direct merge from refWdDevUpdate branch (copy of dev - only ref/wd page) to stage (instead of cherry-pick (many fixes get added and removed. To prevent missing out issues)
ref/wd: Refusal/Withdrawal
> SiteManger Dashboard: Updated ref/wd on Stage

- siteManagerDashboard/participantWithdrawalForm.js
> [SiteManager Dashboard]: Refusal/Withdrawal ->  Nested Who Requested for Refused Some Actvities

- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Added no refusal text for Participant with suspended date in All Participants page

- siteManagerDashboard/index.js
- Updated scheduled query in Big Query
- Updated code for initial survey metrics
> Fixed initial survey metrics

- siteManagerDashboard/index.js
- Updated code calculating number of participants who finished all  4 modules and all 3 baseline samples
> Fixed metric value

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantWithdrawalForm.js
> SiteManaager Dashboard: Updated concept ids for Participantion Status & responses are only set to concepts ids 

- siteManagerDashboard/fieldToConceptIdMapping.js
> SiteManaager Dashboard: Updated concept ids for Participantion Status & responses are only set to concepts ids PART 2

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Added new CID for Who Requested for Suspended contact

- siteManagerDashboard/notifications/storeNotifications.js
> SiteManager Dashboard: Update Edit Functionality of Notification Schema

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummaryRow.js
Title^^
PoC: 
->  payment refused, Connect ID 4128619149
-> incentive issued, Connect ID 1309381426
> SiteManaer Dashboard: Incentive extra field added to Participant Summary

- siteManagerDashboard/participantSummaryRow.js
> SiteManager Dashboard: Incentive extra field added to Participant Summary

- siteManagerDashboard/notifications/storeNotifications.js
The fix makes sure previously stored Notification schema are removed from local storage.
> SiteManager Dashboard: [HOTFIX] Added fix for notification schema disappearing

- siteManagerDashboard/participantSummary.js
> SiteManager Dashboard: Added updated coordinates for UCM

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
> SiteManager Dashboard: Synced notification schema form dev to stage

- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Who requested disabled when participant deceased is selected

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
> SiteManager Dashboard: Synced dev to stage (#359)

- siteManagerDashboard/participantWithdrawalForm.js
- siteManagerDashboard/participantWithdrawalRender.js
> SiteManager Dashboard: Updated CID for refusal/withdrawal reasons

- siteManagerDashboard/participantWithdrawalForm.js
> SiteManager Dashboard: Removed temporarily disabled Who requested

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
adding <, >, <=, and >= functionality to notifications specifications
> adding greater less functionality

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
New dropdown menu for each condition that lets you set the value type as a number or a string
> enabling compare to string or number

- siteManagerDashboard/utils.js
temporarily need these back in
> Revert "removing shared functions"

- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Reset Participant Commons

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
temporarily removing from stage
> Revert "enabling compare to string or number"

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
temporarily removing from stage
> Revert "adding greater less functionality"

- siteManagerDashboard/utils.js
Reverts episphere/dashboard#388
> Revert "removed shared functions"

- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/utils.js
Removing shared functions from stage
> Dev / Stage Sync 071122

- siteManagerDashboard/index.js
- siteManagerDashboard/participantDetails.js
> Stage / Prod Sync 071122

- siteManagerDashboard/index.js
> SiteManager Dashboard: Added alert message on home screen to prevent entering real data

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
restoring notifications changes
> Revert "Revert "enabling compare to string or number""

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
restoring notifications changes
> Revert "Revert "adding greater less functionality""

- siteManagerDashboard/notifications/storeNotifications.js
> SiteManager Dashboard: Added newsletter condition to prevent email body from edits

- siteManagerDashboard/notifications/storeNotifications.js
> SiteManager Dashboard: Removed comments

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
[#402](https://github.com/episphere/dashboard/issues/402)
> SiteManager Dashboard: Rename filter name on Participants Common

- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Rename Filter Last Name in custom label

- siteManagerDashboard/index.js
https://github.com/episphere/dashboard/issues/396
> SiteManager Dashboard: Removed duplicate active recruits from Active Cummulative Status (funnel)

- siteManagerDashboard/index.js
Title^^
https://github.com/episphere/dashboard/issues/394
> SiteManager Dashboard: Count Adjustment for Modules 2-3 survey and Modules None

- siteManagerDashboard/index.js
- siteManagerDashboard/participantLookup.js
List of changes moved to Stage from Dev
https://github.com/episphere/dashboard/pull/422
https://github.com/episphere/dashboard/pull/423
> Merge Dev to Stage

- siteManagerDashboard/index.js
> SiteManager Dashboard: Added none moduel section for inital survey

- siteManagerDashboard/index.js
https://github.com/episphere/dashboard/issues/396
Related PR:
https://github.com/episphere/dashboard/pull/422
> SiteManager Dashboard: Removed duplicates from active recruit charts

- siteManagerDashboard/index.js
> SiteManager Dashboard: Changed total metrics logic utilizes data from active & passive metrics

- siteManagerDashboard/index.js
List of changes added to prod:
-> Refactored metrics chart (total) logic
> Merge Stage to Prod

- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Changed limit to 5 from 1 in Participants Common

- siteManagerDashboard/index.js
Related PR: https://github.com/episphere/dashboard/pull/436
> SiteManager Dashboard: Changed limit to 5 from 1 in index.js

- siteManagerDashboard/index.js
> SiteManger Dashboard: Updated no ssn filter for accurate results

- siteManagerDashboard/participantCommons.js
Title^^
Related PR: https://github.com/episphere/dashboard/pull/435
> SiteManager Dashboard: Added extra condition for next pagination

- siteManagerDashboard/participantSummaryRow.js
> SiteManage Dashboard: Changed clinical blood/urine data mapping

- siteManagerDashboard/participantCommons.js
Title^^
Bug Fix 1: Set Page to 0 when a new filter is selected, prevents resuming from current page
Bug Fix 2: For remapping added && operator to check truthy condition for filters.nextPageCounter
Bug Fix 3: When Bubble filters are selected added a condition that prevents filters from getting reinitialized
Related PR: #440 #435
> SiteManager Dashboard: Minor bug fixes in Filtration & Pagination

- siteManagerDashboard/participantCommons.js
https://github.com/episphere/dashboard/issues/290
-> Added a page number 
-> User can select filters randomly
-> Fixed active button
Related PR: https://github.com/episphere/dashboard/pull/440 https://github.com/episphere/dashboard/pull/435 https://github.com/episphere/dashboard/pull/442
> SiteManager Dashboard: Added additional changes to Filtration & Pagination

- siteManagerDashboard/siteKeysToName.js
https://github.com/episphere/dashboard/issues/290
-> Added a placeholder site code for all site
Related PR: https://github.com/episphere/dashboard/pull/440 https://github.com/episphere/dashboard/pull/435 https://github.com/episphere/dashboard/pull/442 https://github.com/episphere/dashboard/pull/443
> SiteManager Dashboard: Added all site bug fix

- siteManagerDashboard/participantCommons.js
https://github.com/episphere/dashboard/issues/290
-> Addressed Pagination/Page Number Bug fix
-> Sorted bubble filters in alphabetical order
-> Added left padding for Filter by Verification Status Time title
Related PR: https://github.com/episphere/dashboard/pull/440 https://github.com/episphere/dashboard/pull/435 https://github.com/episphere/dashboard/pull/442 https://github.com/episphere/dashboard/pull/443 https://github.com/episphere/dashboard/pull/444
> SiteManager Dashboard: Addressed Pagination/Page Number Bug fix

- siteManagerDashboard/participantSummaryRow.js
Title^^
Related PR: 
https://github.com/episphere/dashboard/pull/447
https://github.com/episphere/dashboard/pull/441
> SiteManager Dashboard: Added default research setting for mouthwash

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummaryRow.js
Release Changes
- Added CID constants for Clinical Blood Date / Time & Clinical Urine Date / Time
- Added Clinical Blood / Urine Date to Participant Summary
- Added function setSampleDateTime() to set Biospecimen sample date appropriately
> Stage / Prod Sync (Clinical Soft Launch)

- siteManagerDashboard/utils.js
> SiteManager Dashboard: Removed commented url from utils.js

- newsletter/index.html
> Newsletter: Remove view in browser hyperlink

- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantWithdrawalForm.js
* Updating payload structure to match expectations of Update Participant Data API
* Bug fix to update CID 371067537 when changes made to participant DOB in User Profile
> Stage / Prod Sync 120822

- siteManagerDashboard/participantSummary.js
tied to issue 204
add in the "cursor: pointer" attribute to the style.
> update cursor to pointer for the download link

- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Added URL import

- siteManagerDashboard/index.js
- siteManagerDashboard/participantChartsRender.js
> SiteManager Dashboard: Updated ssn metrics to reflect update SSN query

- newsletter/index.html
> Newsletter: Rehosting newsletter winter 2022 

- siteManagerDashboard/index.js
- siteManagerDashboard/participantCommons.js
> SiteManager Dashboard: Updated records per page from 5 to 50 for Participant All table

- siteManagerDashboard/index.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantSummary.js
-> https://github.com/episphere/dashboard/issues/290
> SiteManager Dashboard: Added pagination edge case fix for back to search

- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
This PR is to address issue https://github.com/episphere/connect/issues/613
* Adding Datadog RUM to frontend code
* Config used is based on tier code is running in
> Adding Datadog RUM

- siteManagerDashboard/index.html
- siteManagerDashboard/index.js
This PR removes RUM during local development. It updates PR [#487](https://github.com/episphere/dashboard/pull/487), to resolve issue [#613](https://github.com/episphere/connect/issues/613).
> No RUM  in local development

- newsletter/anniversary.html
- newsletter/thankyou.html
> [Newsletter] Updated GIF links for upcoming newsletters

- siteManagerDashboard/participantSummary.js
Title^^
This PR addresses following issue: #496 
Related PR: #500 & #501
> SiteManager Dashboard: Participant Summary added fallback for middle name & suffix with empty string

- newsletter/thankyou.html
> Newsletter: Updated image url in newsletter for view in browser mode

- siteManagerDashboard/participantSummary.js
Title^^
This PR addresses following issue: https://github.com/episphere/dashboard/issues/496
Related PR:
https://github.com/episphere/dashboard/pull/503 https://github.com/episphere/dashboard/pull/501 https://github.com/episphere/dashboard/pull/499
> SiteManger Dashboard Updated kpga coordinates HIPAA form v1

- newsletter/anniversary.html
> Newsletter: Changed hyperlink color in Anniversary Newsletter

- siteManagerDashboard/assets/css/dashboard.css
- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/utils.js
Title^^
Added feature back into DEV!
Original PR: https://github.com/episphere/dashboard/pull/498
> SiteManager Dashboard: Integrated UI to switch login & update login method

- newsletter/thankyou.html
Related PR:
https://github.com/episphere/dashboard/pull/502
https://github.com/episphere/dashboard/pull/515
PR addresses the following issue: https://github.com/episphere/dashboard/issues/491
> Newsletter: Updated text in Thank You newsletter for view in browser

- siteManagerDashboard/participantDetails.js
Title^^
Move reload participant into timeout & reduced timeout by 1 second
Related PR: https://github.com/episphere/dashboard/pull/511
> SiteManager Dashboard: Integrated UI to switch login & update login method part 2

- newsletter/maynewsletter.html
Title^^
This PR addresses following issue: https://github.com/episphere/dashboard/issues/508
Related PR: https://github.com/episphere/dashboard/pull/513
https://github.com/episphere/dashboard/pull/514
> Newslette: Added additional content for May Newsletter

- newsletter/maynewsletter.html
Title^^
This PR addresses following issue: https://github.com/episphere/dashboard/issues/508
Related PR: 
https://github.com/episphere/dashboard/pull/513
https://github.com/episphere/dashboard/pull/514
https://github.com/episphere/dashboard/pull/519
> Newsletter: Increased border in may newsletter in browser version

- newsletter/maynewsletter.html
Title^^
This PR addresses following issue: https://github.com/episphere/dashboard/issues/508
Related PR: https://github.com/episphere/dashboard/pull/513
https://github.com/episphere/dashboard/pull/514
https://github.com/episphere/dashboard/pull/519
https://github.com/episphere/dashboard/pull/521
> Newsletter: Updated May newsletter with feedback

- siteManagerDashboard/participantDetails.js
Title^^
Added alert modal for duplicate & invalid phone numbers & email
Related issue: https://github.com/episphere/dashboard/issues/493
Related PR: 
https://github.com/episphere/dashboard/pull/511
https://github.com/episphere/dashboard/pull/518
> SiteManager Dashboard: Enhanced switch login mechanism UI/UX for error feedback

- .gitignore
- siteManagerDashboard/index.js
- siteManagerDashboard/participantDetails.js
This PR sync PR [#526](https://github.com/episphere/dashboard/pull/526) to stage, allowing only NIH and NORC to change participant login methods. The site restriction functionality is part of feature request in issue [#493](https://github.com/episphere/dashboard/issues/493).
> Move PR #526 to stage

- siteManagerDashboard/index.js
Use Datadog in production ([#648](https://github.com/episphere/connect/issues/648)).
> Use Datadog in prod

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
Title^^
This PR addresses the following issue:
- https://github.com/episphere/dashboard/issues/528
- The nested ternary operators are replaced with if-else statements for improved readability and maintainability
- The optional chaining operator (?.) is used to safely access nested properties without causing an error if they are undefined
> SiteManager Dashboard: Added COVID survey row in Participant Summary page

- siteManagerDashboard/participantDetailsHelpers.js
This addresses multi-logins https://github.com/episphere/dashboard/pull/538
I hadn't handled the response with code other than 200 in this api call.
> add error handling to api call

- siteManagerDashboard/participantDetailsHelpers.js
Issues Addressed:
* https://github.com/episphere/connect/issues/635
> Dev -> Stage Sync (Bug Fix) 071223

- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
This PR addresses the following Issues: 
* https://github.com/episphere/connect/issues/663
Technical Changes:
* Decision was made to remove Site Key login functionality
* Also removing dev Feedback tab as we are live now, sites aren't submitting issues anymore, and Gitter link is stale
> Removing Site Key

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantSummary.js
- siteManagerDashboard/participantSummaryRow.js
- siteManagerDashboard/utils.js
This PR address issue https://github.com/episphere/connect/issues/658
- Updated information of Participant Detail page
- Updated information of Participant Summary page
> [#658] Update participantDetail page && participant Summary page

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummary.js
This Pr addresses comment https://github.com/episphere/connectApp/issues/537#issuecomment-1681270458 of issue https://github.com/episphere/connectApp/issues/537
> [#537] Update participant signature for smdb

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummary.js
This PR addresses comment https://github.com/episphere/connectApp/issues/537#issuecomment-1690340786 of issue https://github.com/episphere/connectApp/issues/537
> [#537] Fix missing suffix

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummary.js
This PR addresses comment https://github.com/episphere/connectApp/issues/537#issuecomment-1693606816 of issue https://github.com/episphere/connectApp/issues/537
> [#537] Update first name and  last name

- newsletter/fallnewsletter.html
Title^^
https://github.com/episphere/connect/issues/705
Related PR:
https://github.com/episphere/dashboard/pull/572
> Newsletter: Update image links

- siteManagerDashboard/index.js
- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/participantChartsRender.js
- siteManagerDashboard/participantLookup.js
- siteManagerDashboard/stateManager.js
This PR update data fetching and UI renderings, to solve issue [#23](https://github.com/episphere/dashboard/issues/23). Below are details:
- Combined 14 separated calls into 1 call, to get metric data from backend.
- For speed, saved metric data are used for a period of time (currently 20 minutes) before doing a new data fetch. There's no need to fetch new data for each dashboard refresh, since backend metric data are updated every 1 hour (in prod).
- Extracted repeated code handling data transformation into a function `transformDataForCharts`, to simplify code for dashboard re-rendering.
- There're 3 different functions having the same name `dropdownTrigger`. Used different names to distinguish them.
- Other updates improving code readability or speed.
> Speed up dashboard loading

- newsletter/fallnewsletter.html
Title^^
https://github.com/episphere/connect/issues/705
> Newsletter: Update URLs in Fall Newsletter

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummaryRow.js
This PR follows PR [#580](https://github.com/episphere/dashboard/pull/580), which implements updates described in issue [#747](https://github.com/episphere/connect/issues/747). Below are update details of PR:
- Granular updates of displayed info, based on overlapped situations.
> Fix mouthwash sample row in "Participant Summary"

- siteManagerDashboard/index.js
- siteManagerDashboard/notifications/storeNotifications.js
- siteManagerDashboard/participantCommons.js
This PR fixes 2 recent errors described in [#748](https://github.com/episphere/connect/issues/748):
- `clearLocalStorage` not defined
- `updateSchemaNotification` is null
Also fixed some typos not identified before.
> Fix 2 errors caught in DataDog

- newsletter/decembernewsletter.html
this PR addresses issue https://github.com/episphere/connect/issues/830
> [#830] Add December eNewsletter

- newsletter/decembernewsletter.html
This PR addresses issue https://github.com/episphere/connect/issues/830
> [#830] Correct wrong month

- newsletter/decembernewsletter.html
This PR addresses comment of Deanna https://github.com/episphere/connect/issues/830#issuecomment-1850210481
> [#830] Update content of spotlight

- newsletter/decembernewsletter.html
This PR addresses comment of Deanna https://github.com/episphere/connect/issues/830#issuecomment-1851034806
> [#I830] Add the "View in browser" back

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
This PR fixes a data synchronization bug in [PR#601](https://github.com/episphere/dashboard/pull/601).
> Fix schema update bug

- siteManagerDashboard/notifications/storeNotifications.js
This PR fixes new schema save issue in [PR#601](https://github.com/episphere/dashboard/pull/601).
> Fix new schema save issue

- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
This PR fix errors when schemas cannot be found. It's an update to [PR#601](https://github.com/episphere/dashboard/pull/601).
> Draft schema bug fix

- siteManagerDashboard/dataCorrectionsTool.js
- siteManagerDashboard/notifications/retrieveNotifications.js
- siteManagerDashboard/notifications/storeNotifications.js
This late sync push a fix (handling empty schema search result) to stage.
> Dev -> Stage Late Update (Jan. Release)

- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantMessages.js
This PR:
- Improves notification history display ([PR#875](https://github.com/episphere/connect/issues/875))
- Fixes a bug (when `conceptIdMapping` is null, [PR#748](https://github.com/episphere/connect/issues/748))
> Fix notifications display and bug fix

- siteManagerDashboard/participantSummaryRow.js
This PR addresses a bug found in the following Pull Request:
* https://github.com/episphere/dashboard/pull/617
-----
* Request was made to have the survey status not change even if the activity was refused so I took the chance to also refactor / simplify some code
-----
* Refactored `baselinePromisSurvey` in `participantSummaryRow.js`
> PROMIS Survey Updates (Study Manager Dashboard)

- siteManagerDashboard/notifications/storeNotifications.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantDetailsHelpers.js
- siteManagerDashboard/participantHeader.js
- siteManagerDashboard/participantWithdrawal.js
Updates in this PR:
- Fixes on recent errors in SMDB reported in DataDog, detailed in [#748](https://github.com/episphere/connect/issues/748)
- Clean-ups
> Fix errors reported in DataDog

- newsletter/aprilnewsletter.html
This PR addresses Issue https://github.com/episphere/connect/issues/929
> [#929] Implement April newsletter

- newsletter/aprilnewsletter.html
This PR addresses comment https://github.com/episphere/dashboard/pull/635#issuecomment-2043286232
> [#929] Remove dark mode

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantCommons.js
- siteManagerDashboard/participantSummaryRow.js
This PR addresses issue https://github.com/episphere/connect/issues/937
ChangeLog:
- Add condition to check participant status in `partipantCommons.js`
- Remove all condition of checking dataDestroyed in `participantSummaryRow.js`
> [#937] SMDB Participation Status Error for Data Destruction

- siteManagerDashboard/notifications/storeNotifications.js
This PR fixes a bug introduced in [PR #641](https://github.com/episphere/dashboard/pull/641).
> Fix missing schema ID

- siteManagerDashboard/fieldToConceptIdMapping.js
- siteManagerDashboard/participantSummaryRow.js
This PR addresses comment https://github.com/episphere/connect/issues/937#issuecomment-2062324891
> [#937] Update the status of the  SSN survey

- newsletter/anniversary.html
Reverts episphere/dashboard#639
> Revert "[#944] Remove dark mode"

- siteManagerDashboard/participantDetails.js
- siteManagerDashboard/participantDetailsHelpers.js
Updates in this PR:
- Fix empty string values for variables d_271757434 ([issue #979](https://github.com/episphere/connect/issues/979)) and d_646873644 ([issue #976](https://github.com/episphere/connect/issues/976))
- Code cleanups
> Fix empty string bugs

- siteManagerDashboard/participantWithdrawalForm.js
This PR addresses issue https://github.com/episphere/connect/issues/996
ChangeLog
- Set CID 861639549 = 104430631 when user request data destroy.
> [#I996] Data Destruction Fix - Address backlog of participants with incorrect default variable

- siteManagerDashboard/notifications/storeNotifications.js
This PR implements functionality of adding Spanish email/SMS templates to existing or new notification specs. It's part of implementation needed in [issue #918](https://github.com/episphere/connect/issues/918).
> Update SMDB Notification Spec editing UI for Spanish

- siteManagerDashboard/notifications/storeNotifications.js
This PR removes limit on message length as requested. 
It follows [PR#659](https://github.com/episphere/dashboard/pull/659) and is part of implementation needed for [issue#918](https://github.com/episphere/connect/issues/918).
> Remove limit on message length

- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
This PR addresses the following Issue:
* N/A
-----
* This dashboard has been forked and is moving to a new location
-----
* Comment out code in `index.js` and `navigationBar.js`
* Updated message on home page
> Remove SSO Login

- siteManagerDashboard/index.js
- siteManagerDashboard/navigationBar.js
SMDB has been transferred to a different repository, removing the SSO Login feature on this repository.
> Removing SSO
