siteManagerDashboard/participantCommons.js
siteManagerDashboard/participantDetails.js
siteManagerDashboard/participantLookup.js

This PR addresses the following feature:
-> Address #42 feature request
-> User can go back to search results on Participant Lookup from Participant Details upon clicking Back to Search button
on Participant Details
Checklist:
Test case 1:
Search for users with same first name, select one of them from participant lookup. Then on Participant Details,
click Back to Search button on left. Upon clicking, should display Participant Lookup result table.

Site Manager Dashboard : Added back to search results feature on Participant Details

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantCommons.js

This PR addresses fix for following issue:
-> #43 
-> Filtered out column buttons that return json response & duplicate columns. Turned concept IDs to variable names and human readable time/date format
Checklist:
Test Cases Verified: 
**Not Verified Participants**
**All Participants**
PoC:
**Filtered out columns**
**Signed In Status**
**Verified Status**

Site Manger Dashboard: Filtered out column buttons that return json response & duplicate columns

---

siteManagerDashboard/index.js
siteManagerDashboard/navigationBar.js
siteManagerDashboard/participantDetails.js
siteManagerDashboard/participantSummary.js
siteManagerDashboard/participantWithdrawal.js
siteManagerDashboard/participantWithdrawalForm.js

This PR addresses the following features & fixes:
-> Participant Withdrawal, lets the user refuse activities, surveys, & others 
Checklist:
Notes: 
**Concept IDs for refusal activity/surveys aren't created. Until then, upon hitting submit only console logs the responses 
recorded.
Once concept IDs are created, `updateParticipants` API would be integrated.**
Test case 1:
**Upon checking Participant Deceased option, the page should be redirected to screen for deceased**
Test case 2:
**Upon checking Destroy Data option, following options should be auto selected _Refusing all future activities_, _Revoke HIPAA authorization (no medical records)*_, _Withdraw consent_. Upon hitting next, the page should be redirected to screen for all refusal/withdrawal choices**
Test case 3:
**If no options are …

Site Manager Dashboard : Participants Withdrawal

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/index.html
siteManagerDashboard/index.js
siteManagerDashboard/navigationBar.js
siteManagerDashboard/participantDetails.js
siteManagerDashboard/participantHeader.js
siteManagerDashboard/participantLookup.js
siteManagerDashboard/participantSummary.js
siteManagerDashboard/participantSummaryRow.js
siteManagerDashboard/participantWithdrawal.js
siteManagerDashboard/participantWithdrawalForm.js
siteManagerDashboard/utils.js

This PR addresses the following features & issues (#58 #66):
-> Participant Withdrawal, api call integrated & concept ids added to options
-> Added necessary participant summary variables
-> Participant Withdrawal only available to parent site keys
Checklist:
Notes: 
Pending: Add date fields, update participant status variable, fix All option on Filter by Site option
Test case 1:
**Check for updated Participant Status on Participant Header after api call**
Test case 2:
**Participant withdrawal only available for participant parent site key**

Participant withdrawal feedback

---

siteManagerDashboard/participantSummaryRow.js

-> In participant JSON response, (Full/Half) SSN survey default is set to no. This PR sets SSN flag to green check
only if Full/Half) SSN survey default is set to yes.

[HotFix] Fixed Participant Summary SSN SURVEY bug

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantWithdrawalForm.js

Added following concept ids; date requested in withdrawal status:
https://episphere.github.io/conceptGithubActions/web/#659990606
https://episphere.github.io/conceptGithubActions/web/#269050420
https://episphere.github.io/conceptGithubActions/web/#664453818
PoC:

[Site Manager Dashboard] Add date requested Participant Withdrawal

---

siteManagerDashboard/participantWithdrawalForm.js

-> _In scenario 5, when trying to suspend the case until December 1st.   We enter in the date,  and also selected a value for “who requested”, but after hitting next the pop up says: Select an option & requested by before proceeding.  It seems to want us to pick something on the left hand side of the screen, but I thought that was supposed to be blank for suspended cases._

[HotFix] Fixed Suspend Contact 

---

siteManagerDashboard/participantHeader.js
siteManagerDashboard/participantWithdrawal.js
siteManagerDashboard/participantWithdrawalForm.js

**This PR addresses following issue:**
_In scenario 8, we had the participant refuse to do future samples one day, and then want to withdraw the next.     When we went in to do the withdrawal,  it won’t let us enter it.   We check withdrawal, requested by participant, but the “next” button is never activated._
**Checklist:**
**PoC:**
**Test Case 1:** User can change Participant with suspended contact to refusal 
**Test Case 2:** User with suspended contact can change Participant to refusal activity

[HotFix] Participant Withdrawal Feature Request

---

siteManagerDashboard/participantCommons.js

-> Clear active/passive filter when double clicked
-> Shows an empty table when they're no participants

SiteManager Dashboard: fixed active/passive double click filter btn & no results for site

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantCommons.js

Removed email filter from Participants Table

SiteManager Dashboard: Removed email filter from Participants Table

---

siteManagerDashboard/index.js

Moved local storage from reRenderTableParticipantsAllTable to renderParticipants table function to prevent overload of local storage
PR addresses following Issue: https://github.com/episphere/dashboard/issues/414
Related PR: https://github.com/episphere/dashboard/pull/415

SiteManager Dashboard: Moved local storage from reRenderTableParticipantsAllTable to render Pts table

---

siteManagerDashboard/index.js
siteManagerDashboard/participantCommons.js
siteManagerDashboard/stateManager.js
siteManagerDashboard/utils.js

https://github.com/episphere/dashboard/issues/290
-> Selected filters pertain after clicking on Back to Search button on Participants Details
-> Utilized State Management to track filters
Checklist:
Notes: 
-> Reduced API call for better performance. Remap of filter from back to search triggered from index.js instead of participantsCommons.js
-> Refresh the page to select new filter(s) for better results accuracy
Test case 1:
**Selected Filters should pertain after clicking back to search**
Test case 2:
**After returning from back to search, upon clicking next should still pertain filters selected**

SiteManager Dashboard: Updated Back to Search functionality

---

siteManagerDashboard/participantDetails.js

Added in lines 306 - 312:
If the birth month, birth day, or birth year are updated then we need to update the full date of birth field.
Used the changedOption to get the day/month/year value when in the changedOption array so if a user updates day and month before saving then the full date of birth will have the new day/month combo.
Added in an id field equal to the conceptId on line 188
this was to make it easier to find the birth day fields to concatenate

SiteManager Dashboard: DOB CID update

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantDetails.js
siteManagerDashboard/participantDetailsHelpers.js
siteManagerDashboard/utils.js

This PR addresses [issue #635](https://github.com/episphere/connect/issues/635) - User Profile Archiving - in SMDB.
• Refactored participantDetails.js for readability & maintainability (removed most embedded logic and modularized code).
• Added user profile editing functionality (Firestore write to user profile).
• Added user profile archiving (Firestore write to user profile).
Only archive profile for verified participants.
Added ‘who requested change’ conceptId 611005658. This is a new requirement.
• Editable item toggling: once verified, date of birth items (day, month, year) are no longer editable.
• Implemented dropdown selectors for all selectable fields (day, month, state, suffix).
• Implemented validation on all non-selectable items.
• Differentiated between required and optional …

Update User Edit Functionality & Profile Archiving - SMDB

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantWithdrawalForm.js

This PR updates SMDB to set `8836684441` to `111959410` when a user requests data destruction in SMDB.
SMDB User withdrawal:
The conceptId `831041022` ‘Destroy Data : Wants data destroyed’
is a yes/no variable. It is getting set to `355358909`  ‘yes’ when a user submits the withdrawal form in SMDB.
The conceptId dictionary also contains the following variables for data destruction:
`883668444` = Destroy data categorical, associated with these options:
`457944265` = ‘Current Question Text: Not requested’
`111959410` = ‘Current Question Text:  Requested but not signed’
`704529432` = ‘Current Question Text:  Requested and signed’
The status: 'requested but not signed' is needed for our automated data destroy tasks. At this point in the flow, data destruction has been requested, but the …

bug fix - write dataDestroyCategorical in SMDB

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/index.js
siteManagerDashboard/participantDetails.js
siteManagerDashboard/participantDetailsHelpers.js
siteManagerDashboard/participantHeader.js

This PR addresses multiple login options in SMDB.
It is a newly requested update to Abhinav's switch login mechanism [update #493](https://github.com/episphere/dashboard/issues/493) 
-Participant can have max 1 email and 1 phone auth method
-Only one method is required
-phone auth can only be removed if email auth exists
-email auth can only be removed if phone auth exists
-both firebase Auth and the participant’s firestore profiles are updated
Important workaround:
There is an issue where Firebase Auth doesn’t allow email removal.
The ops team wanted email removal to be an option for participants.
To work around this: on email removal request, we:
—update the participant `firebase auth email` to `noReply${uid}@episphere.github.io]`
—update the firestore participant’s `firestore profile` …

Smdb multiple authentication methods

---

siteManagerDashboard/fieldToConceptIdMapping.js

Wrong CID was entered in this [issue](https://github.com/episphere/dashboard/issues/528) & 
upon cross check came across correct COVID Flag CID: 220186468
**Required for upcoming Stage/Prod June release**
Related PR: https://github.com/episphere/dashboard/pull/539
PoC:

SiteManager Dashaboard: Updated covid flag CID in Participant Summary

---

siteManagerDashboard/participantDetailsHelpers.js

Update to https://github.com/episphere/dashboard/pull/531
Fix error in dob handling. A bad reference was causing dob to be written incorrectly when 2 or more dob fields were updated.
The fix: make the dateOfBirthComplete write explicit.

error fix: update dob handling

---

siteManagerDashboard/participantCommons.js
siteManagerDashboard/participantDetailsHelpers.js
siteManagerDashboard/participantLookup.js

This PR is in support of:
https://github.com/episphere/connect/issues/654
And
https://github.com/episphere/dashboard/pull/538
Re: Expand name search:
•Write updates to `query.firstName` and `query.lastName` fields as arrays.
`query.firstName` field includes: consent first name (471168198), first name (399159511), and preferred name (153211406).
`query.lastName` field includes: consent last name (736251808) and last name(996038075).
Re: Multi-logins:
•Fix handling of `phone`, `password`, and `passwordAndPhone` sign-in mechanism reporting (995036844). The issue was: ‘noreply’ emails were not factored into the reporting functionality, so removed emails were causing incorrect reporting of sign-in mechanism.
•Hide ‘noreply’ account emails in the participant lookup results. I am now aware that …

expand name search & fix login-mechanism reporting

---

siteManagerDashboard/participantLookup.js

Supporting: https://github.com/episphere/connect/issues/654 - expanded name search.
Remove a console.log() statement I missed - logging a query string during search

remove console.log() query string

---

siteManagerDashboard/assets/css/dashboard.css
siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/index.html
siteManagerDashboard/index.js
siteManagerDashboard/participantChartsRender.js
siteManagerDashboard/participantSummary.js
siteManagerDashboard/participantSummaryRow.js

This PR implements updates requested in [#747](https://github.com/episphere/connect/issues/747). Below are details:
- Updated count in top right corner card, and also texts
- Updated counts in bottom right plot
- Implemented suggested changes in "Baseline/Survey/Home Mouthwash" and "Baseline/Sample/MouthWash" rows
- Full screen table display in 'Participant Summary' tab
- Code cleanup for clarity
Besides updates in current SMDB repo, scheduled queries (`participants_allModules`, `participants_biospecimen`) generating tables for metrics were also updated

Updates for home mouthwash

---

siteManagerDashboard/participantSummaryRow.js

This PR follows PR [#580](https://github.com/episphere/dashboard/pull/580) and PR [#582](https://github.com/episphere/dashboard/pull/582), to  implements updates described in issue [#747](https://github.com/episphere/connect/issues/747). Below are details of the updates in baseline/sample/mouthwash row in 'Participant Summary':
- Display date only after sample is received
- Use mouthwash collection date (448660695)

Home mouthwash update 3

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantSummary.js
siteManagerDashboard/participantSummaryRow.js

This PR addresses the following Issue:
* https://github.com/episphere/connect/issues/878
-----
* With the new PROMIS QOL Survey being added to the study we need to display the status of the survey for each participant on the Participant Summary page.
-----
* Added new survey status Concept ID and PROMIS survey Concept IDs to `fieldToConceptIdMapping.js`
* Added HTML block to `participantSummary.js`
* Added function `baselinePromisSurvey()` to `participantSummaryRow.js` to calculate and render row for PROMIS survey

PROMIS Survey Updates (Study Manager Dashboard)

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantCommons.js
siteManagerDashboard/participantSummaryRow.js
siteManagerDashboard/participantWithdrawal.js
siteManagerDashboard/participantWithdrawalForm.js

This PR addresses the following Issues:
* https://github.com/episphere/connect/issues/878
* https://github.com/episphere/connect/issues/881
-----
* With the new PROMIS QOL Survey being added to the study we need to add a couple of new options on the Participant Refusal / Withdrawals page
-----
* Added new Concept ID constants to `fieldToConceptIdMapping.js`
* Added new `renderTable()` column headers and `tableTemplate()` data row values in `participantCommons.js`
* Updated and cleaned up `baselinePromisSurvey()` in `participantSummaryRow.js`
* Added new options to `getParticipantSelectedRefusals()` in `participantWithDrawal.js`
* Added new check boxes and timestamps to `participantWithdrawalForm.js`

QOL Survey Refusal Options

---

siteManagerDashboard/fieldToConceptIdMapping.js

This PR addresses the following:
- https://github.com/episphere/connect/issues/901
- https://github.com/episphere/connect/issues/901#issuecomment-1979385034
**Problem: 10 digit concept Id was being used for BioKit_Mouthwash**
Update BioKit_Mouthwash concept Id from `8583443674` to `319972665`

Update BioKit_Mouthwash Assembly Concept ID 

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/participantCommons.js
siteManagerDashboard/participantSummaryRow.js
siteManagerDashboard/participantWithdrawal.js
siteManagerDashboard/participantWithdrawalForm.js

This PR is partially related to [issue#894](https://github.com/episphere/connect/issues/894)
Related links:
- https://github.com/episphere/connect/issues/894#issuecomment-1944280449
Problem:
The dateHipaaRevokeRequested (664453818) and refusedSpecimenSurveys (217367618) are referencing the `getCustomVariableNames` function in the mapping ternary logic. The concept Ids are suppose to reference the variable label value.
Code Changes:
- Removed `x !== fieldMapping.refusedSpecimenSurevys` and `x !== fieldMapping.dateHipaaRevokeRequested` from the mapping ternary logic so it doesn't reference `getCustomVariableNames` function
- Updated `refusedSpecimenSurveys` typo
- Remove `fieldMapping.refusedSpecimenSurevys` and `fieldMapping.dateHipaaRevokeRequested` in `getCustomVariableNames` function …

Display concept ids for dateHipaaRevokeRequested and refusedSpecimenSurveys correctly

---

siteManagerDashboard/participantHeader.js

This pull request is related to issue#894 in the study manager dashboard:
- https://github.com/episphere/connect/issues/894
Problem:  Error in display fields in header for consent date and verification date. Concept Ids were being displayed instead of dates due to variable label changes in the `getMappings` function that fetches `https://raw.githubusercontent.com/episphere/conceptGithubActions/master/aggregate.json`
Code Changes:
Replace conditionals with updated variable labels

SMDB - Error in display fields in header for consent date and verification date

---

siteManagerDashboard/notifications/storeNotifications.js

This PR follows [PR #640](https://github.com/episphere/dashboard/pull/640), to make the dry run UI immediately appears after saving a new schema.

Fix dry run UI lagging when saving a new schema

---

newsletter/anniversary.html

This PR addresses issue https://github.com/episphere/connect/issues/944
ChangeLog:
- Remove `style` in `header`
- Used `text-align` instead of `display: flex` and `justify-content` since it does not work in gmail.
- Remove darkmode
- Re-indent source code

[#944] Fix: Formatting does not work in gmail from browser

---

siteManagerDashboard/fieldToConceptIdMapping.js
siteManagerDashboard/index.js
siteManagerDashboard/participantCommons.js
siteManagerDashboard/participantLookup.js
siteManagerDashboard/participantSummary.js

The pull request is related to the following links:
Add BSWH reported race/ethnicity button field on All Participants page
- https://github.com/episphere/connect/issues/1035
Fix dropdown for BSWH and add cursor pointer on HIPAA consent copy link on hover
- https://github.com/episphere/connect/issues/884#issuecomment-2130060601 
---
Code Changes:
- Added `bswhReportedRaceEthnicity` reference to `fieldToConceptIdMapping.js` for bswh reported race/ethnicity field button
- Added new race/ethnicity references in `fieldToConceptIdMapping.js`
- Added logic to display bswh participant's reported race/ethnicity on table
- Adjusted order of BSWH on dropdown so it's alphabetical relative to the filter options
---
BSWH in filter dropdown option
BSWH reported race/ethnicity button field
BSWH reported …

Add BSWH race/ethnicity smdb bubble fields & other fixes

---

siteManagerDashboard/participantCommons.js

This pull request is related to the links below:
Previous issue
- https://github.com/episphere/connect/issues/1035
Adjust placement of bswh reported race/ethnicity bubble filter to be with other related reported race/ethnicity bubbles
- https://github.com/episphere/connect/issues/1035#issuecomment-2159206942
Code Changes:
- Moved `fieldMapping.bswhReportedRaceEthnicity` after `fieldMapping.henryFReportedRace` in array of bubble filter references

Move bswh reported r/e bubble filter on participants page
